"""Evidence register and chain-of-custody verification.

The Berkeley Protocol on Digital Open Source Investigations (UN Human Rights,
2022) requires that an investigation be able to demonstrate, for every item it
relies on, where the item came from, when it was acquired, who handled it, and
that it has not changed since. `src.integrity` provides the hashing primitive;
this module builds the register around it.

The verification here is real, not illustrative. Hashes are computed over the
actual project artifacts and compared against a committed manifest
(`data/evidence_manifest.json`), so editing any registered file makes the
register report ALTERED on the next run. That is the whole point of a custody
record: it fails loudly when the underlying material moves.

Regenerate the manifest after any intentional change to a registered artifact:

    python -m src.evidence
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from src.config import BASE_DIR, DATA_DIR
from src.integrity import sha256_file

MANIFEST_PATH = DATA_DIR / "evidence_manifest.json"

STATUS_VERIFIED = "VERIFIED"
STATUS_ALTERED = "ALTERED"
STATUS_MISSING = "MISSING"
STATUS_UNREGISTERED = "UNREGISTERED"


@dataclass(frozen=True)
class Artifact:
    """A project artifact placed under custody control."""

    exhibit_id: str
    description: str
    relative_path: str
    origin: str
    handling: str


# Every artifact the analytical outputs actually depend on. If a file here is
# edited, conclusions drawn from it are no longer reproducible — which is
# precisely what the register is meant to reveal.
REGISTERED_ARTIFACTS: tuple[Artifact, ...] = (
    Artifact(
        exhibit_id="EX-001",
        description="Southeast Asia seizure dataset (synthetic, Admiralty-rated)",
        relative_path="data/sea_drug_seizures.csv",
        origin="Generated by data/build_dataset.py; modeled on published UNODC trends",
        handling="Unrestricted — synthetic data, no personal or non-public information",
    ),
    Artifact(
        exhibit_id="EX-002",
        description="Dataset build and source-rating derivation script",
        relative_path="data/build_dataset.py",
        origin="Authored for this project",
        handling="Unrestricted",
    ),
    Artifact(
        exhibit_id="EX-003",
        description="Illustrative sanctions reference set",
        relative_path="src/blockchain/sanctions.py",
        origin="Derived from published OFAC designations plus placeholder entries",
        handling="Unrestricted — verify against the live OFAC SDN list before any real use",
    ),
    Artifact(
        exhibit_id="EX-004",
        description="Pre-cached synthetic transaction data used in demo mode",
        relative_path="src/blockchain/demo_data.py",
        origin="Synthesised for this project",
        handling="Unrestricted — synthetic",
    ),
    Artifact(
        exhibit_id="EX-005",
        description="Worked ACH scenario: hypotheses, evidence and source ratings",
        relative_path="src/analysis/scenarios.py",
        origin="Authored for this project; evidence statements are illustrative",
        handling="Unrestricted",
    ),
)


@dataclass
class RegisterEntry:
    """One line of the evidence register, as presented to a reader."""

    exhibit_id: str
    description: str
    origin: str
    handling: str
    relative_path: str
    acquired_utc: str
    size_bytes: int
    sha256: str
    status: str


def _utc_iso(timestamp: float) -> str:
    return datetime.fromtimestamp(timestamp, tz=timezone.utc).strftime(
        "%Y-%m-%d %H:%M:%SZ"
    )


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def _artifact_state(artifact: Artifact) -> dict | None:
    """Hash an artifact and capture its acquisition metadata, or None if absent."""
    path = BASE_DIR / artifact.relative_path
    if not path.exists():
        return None
    stat = path.stat()
    return {
        "sha256": sha256_file(path),
        "size_bytes": stat.st_size,
        "acquired_utc": _utc_iso(stat.st_mtime),
    }


def build_manifest() -> dict:
    """Compute the current custody manifest for all registered artifacts."""
    entries = {}
    for artifact in REGISTERED_ARTIFACTS:
        state = _artifact_state(artifact)
        if state is None:
            continue
        entries[artifact.exhibit_id] = {
            "relative_path": artifact.relative_path,
            **state,
        }
    return {
        "generated_utc": now_utc_iso(),
        "hash_algorithm": "SHA-256",
        "artifacts": entries,
    }


def load_manifest() -> dict | None:
    """Read the committed manifest, or None if it has not been generated."""
    if not MANIFEST_PATH.exists():
        return None
    try:
        with open(MANIFEST_PATH, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None


def write_manifest(manifest: dict | None = None) -> Path:
    """Write the manifest to disk, establishing a new custody baseline."""
    manifest = manifest or build_manifest()
    with open(MANIFEST_PATH, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return MANIFEST_PATH


def verify_register() -> list[RegisterEntry]:
    """Re-hash every registered artifact and compare against the manifest.

    Returns one entry per artifact with a status of VERIFIED, ALTERED, MISSING
    or UNREGISTERED. UNREGISTERED means the file exists but has no manifest
    baseline to check it against, so its integrity is simply unknown — reported
    as such rather than assumed good.
    """
    manifest = load_manifest() or {}
    baselines = manifest.get("artifacts", {})

    entries: list[RegisterEntry] = []
    for artifact in REGISTERED_ARTIFACTS:
        state = _artifact_state(artifact)
        if state is None:
            entries.append(
                RegisterEntry(
                    exhibit_id=artifact.exhibit_id,
                    description=artifact.description,
                    origin=artifact.origin,
                    handling=artifact.handling,
                    relative_path=artifact.relative_path,
                    acquired_utc="—",
                    size_bytes=0,
                    sha256="—",
                    status=STATUS_MISSING,
                )
            )
            continue

        baseline = baselines.get(artifact.exhibit_id)
        if baseline is None:
            status = STATUS_UNREGISTERED
        elif baseline.get("sha256") == state["sha256"]:
            status = STATUS_VERIFIED
        else:
            status = STATUS_ALTERED

        entries.append(
            RegisterEntry(
                exhibit_id=artifact.exhibit_id,
                description=artifact.description,
                origin=artifact.origin,
                handling=artifact.handling,
                relative_path=artifact.relative_path,
                acquired_utc=state["acquired_utc"],
                size_bytes=state["size_bytes"],
                sha256=state["sha256"],
                status=status,
            )
        )
    return entries


def custody_log(entries: list[RegisterEntry]) -> list[dict]:
    """Build the handling log for the register.

    Three event types are recorded, all of them genuine: the artifact's own
    acquisition time, the baseline hashing recorded in the manifest, and the
    verification performed in this session.
    """
    manifest = load_manifest() or {}
    registered_at = manifest.get("generated_utc", "not yet generated")
    verified_at = now_utc_iso()

    log: list[dict] = []
    for entry in entries:
        if entry.status == STATUS_MISSING:
            log.append(
                {
                    "Exhibit": entry.exhibit_id,
                    "Timestamp (UTC)": verified_at,
                    "Action": "Verification failed — artifact not found",
                    "Actor": "Application (automated)",
                }
            )
            continue
        log.extend(
            [
                {
                    "Exhibit": entry.exhibit_id,
                    "Timestamp (UTC)": entry.acquired_utc,
                    "Action": "Acquired / last written",
                    "Actor": "Project build step",
                },
                {
                    "Exhibit": entry.exhibit_id,
                    "Timestamp (UTC)": registered_at,
                    "Action": "SHA-256 baseline recorded in manifest",
                    "Actor": "python -m src.evidence",
                },
                {
                    "Exhibit": entry.exhibit_id,
                    "Timestamp (UTC)": verified_at,
                    "Action": f"Integrity re-verified — {entry.status}",
                    "Actor": "Application (automated)",
                },
            ]
        )
    return log


def register_summary(entries: list[RegisterEntry]) -> dict:
    """Aggregate counts by status, for headline reporting."""
    return {
        "total": len(entries),
        "verified": sum(1 for e in entries if e.status == STATUS_VERIFIED),
        "altered": sum(1 for e in entries if e.status == STATUS_ALTERED),
        "missing": sum(1 for e in entries if e.status == STATUS_MISSING),
        "unregistered": sum(1 for e in entries if e.status == STATUS_UNREGISTERED),
    }


def main() -> None:
    manifest = build_manifest()
    path = write_manifest(manifest)
    print(f"Wrote custody baseline for {len(manifest['artifacts'])} artifacts to {path}")
    for exhibit_id, data in sorted(manifest["artifacts"].items()):
        print(f"  {exhibit_id}  {data['sha256'][:16]}…  {data['relative_path']}")


if __name__ == "__main__":
    main()
